# Generated by Django 5.0.2 on 2024-03-02 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Piece of news",
                "verbose_name_plural": "Pieces of news",
            },
        ),
    ]
